### ISSUE TITLE
How should use this for an already created vite project?

### ISSUE THREAD

**Issue by StefanGhiban** [nystudio107/vitejs-docker-dev#5]
### Question
Hi! I would like to dockerize an existing frontend application that use vite and vue with typescript. How can I apply this project to my existing setup? Thank you.

**Comment by khalwat** [comment]
This project is a Dockerized environment for working on Vue itself.

If you want to learn how to Dockerize something like your frontend project, check out: https://nystudio107.com/blog/run-your-node-js-apps-buildchains-via-docker
